// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // 💡 Added the seed command directly to the migrations config block
    seed: "node ./prisma/seed.js",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});